"""Document generation proof — cryptographic provenance for rendered PDFs.

Embeds a verifiable proof in the PDF metadata that records how the document
was generated: which template, which data, which engine version, when.

Given the PDF and the original inputs, a verifier can recompute the hashes
and confirm the document was generated by TrustRender from those specific inputs.

This is not a digital signature (no PKI required). It is a generation proof:
it answers "was this document produced from this data using this template?"
without requiring re-rendering.

Proof structure (embedded as PDF metadata keyword ``trustrender:provenance``)::

    {
        "engine": "trustrender",
        "engine_version": "0.1.0",
        "template_hash": "sha256:<hex>",
        "data_hash": "sha256:<hex>",
        "timestamp": "2026-04-10T21:00:00Z",
        "proof": "sha256:<hex>"   # hash of all above fields
    }

Verification::

    from trustrender.provenance import verify_provenance

    result = verify_provenance(pdf_bytes, template_path, data_dict)
    # result.verified == True if hashes match
"""

from __future__ import annotations

import hashlib
import json
import os
from dataclasses import dataclass
from datetime import datetime, timezone
from io import BytesIO
from pathlib import Path

from . import __version__

# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------


@dataclass
class ProvenanceRecord:
    """A document generation proof."""

    engine: str
    engine_version: str
    template_hash: str
    template_name: str
    data_hash: str
    timestamp: str
    proof: str

    def to_dict(self) -> dict:
        return {
            "engine": self.engine,
            "engine_version": self.engine_version,
            "template_hash": self.template_hash,
            "template_name": self.template_name,
            "data_hash": self.data_hash,
            "timestamp": self.timestamp,
            "proof": self.proof,
        }

    @classmethod
    def from_dict(cls, d: dict) -> ProvenanceRecord:
        return cls(
            engine=d["engine"],
            engine_version=d["engine_version"],
            template_hash=d["template_hash"],
            template_name=d["template_name"],
            data_hash=d["data_hash"],
            timestamp=d["timestamp"],
            proof=d["proof"],
        )


@dataclass
class VerificationResult:
    """Result of verifying a document's provenance."""

    verified: bool
    record: ProvenanceRecord | None
    reason: str  # "match", "proof_mismatch", "data_mismatch", "template_mismatch", "no_provenance"


# ---------------------------------------------------------------------------
# Hashing
# ---------------------------------------------------------------------------


def _hash_bytes(data: bytes) -> str:
    """SHA-256 hash of raw bytes."""
    return f"sha256:{hashlib.sha256(data).hexdigest()}"


def _canonical_json(data: dict) -> bytes:
    """Canonical JSON serialization for deterministic hashing.

    Sorted keys, no whitespace, ensure_ascii for cross-platform consistency.
    """
    return json.dumps(data, sort_keys=True, separators=(",", ":"), ensure_ascii=True).encode()


def _compute_proof(
    engine_version: str,
    template_hash: str,
    data_hash: str,
    timestamp: str,
) -> str:
    """Compute the proof hash from all provenance fields."""
    payload = f"{engine_version}|{template_hash}|{data_hash}|{timestamp}"
    return f"sha256:{hashlib.sha256(payload.encode()).hexdigest()}"


# ---------------------------------------------------------------------------
# Provenance creation
# ---------------------------------------------------------------------------


def create_provenance(
    template_path: str | os.PathLike,
    data: dict,
    timestamp: datetime | None = None,
) -> ProvenanceRecord:
    """Create a provenance record for a document generation.

    Args:
        template_path: Path to the template file used.
        data: The data dict used for rendering.
        timestamp: Generation timestamp (defaults to UTC now).
    """
    template_path = Path(template_path)
    template_bytes = template_path.read_bytes()
    template_hash = _hash_bytes(template_bytes)
    data_hash = _hash_bytes(_canonical_json(data))

    if timestamp is None:
        timestamp = datetime.now(timezone.utc)
    ts = timestamp.isoformat()

    proof = _compute_proof(__version__, template_hash, data_hash, ts)

    return ProvenanceRecord(
        engine="trustrender",
        engine_version=__version__,
        template_hash=template_hash,
        template_name=template_path.name,
        data_hash=data_hash,
        timestamp=ts,
        proof=proof,
    )


# ---------------------------------------------------------------------------
# PDF metadata embedding / extraction
# ---------------------------------------------------------------------------

_PROVENANCE_KEY = "trustrender:provenance"


def embed_provenance(pdf_bytes: bytes, record: ProvenanceRecord) -> bytes:
    """Embed a provenance record into PDF metadata.

    Uses pypdf to inject the record as a custom metadata field.
    The provenance is stored as JSON in the PDF's Info dictionary
    under the key ``trustrender:provenance``.

    Uses ``clone_from`` to preserve the full PDF structure (including
    ZUGFeRD embedded files, XMP metadata, and output intents).
    """
    from pypdf import PdfReader, PdfWriter

    reader = PdfReader(BytesIO(pdf_bytes))
    writer = PdfWriter(clone_from=reader)

    # Add provenance
    provenance_json = json.dumps(record.to_dict(), separators=(",", ":"))
    writer.add_metadata({f"/{_PROVENANCE_KEY}": provenance_json})

    out = BytesIO()
    writer.write(out)
    return out.getvalue()


def extract_provenance(pdf_bytes: bytes) -> ProvenanceRecord | None:
    """Extract a provenance record from PDF metadata.

    Returns None if no provenance is found.
    """
    from pypdf import PdfReader

    reader = PdfReader(BytesIO(pdf_bytes))
    if not reader.metadata:
        return None

    raw = reader.metadata.get(f"/{_PROVENANCE_KEY}")
    if not raw:
        return None

    try:
        d = json.loads(str(raw))
        return ProvenanceRecord.from_dict(d)
    except (json.JSONDecodeError, KeyError):
        return None


# ---------------------------------------------------------------------------
# Verification
# ---------------------------------------------------------------------------


def verify_provenance(
    pdf_bytes: bytes,
    template_path: str | os.PathLike,
    data: dict,
) -> VerificationResult:
    """Verify a document's provenance against original inputs.

    Extracts the embedded provenance record from the PDF, then recomputes
    hashes from the provided template and data to check for a match.

    Args:
        pdf_bytes: The PDF document to verify.
        template_path: Path to the template that should have been used.
        data: The data dict that should have been used.

    Returns:
        VerificationResult with ``verified=True`` if all hashes match.
    """
    record = extract_provenance(pdf_bytes)
    if record is None:
        return VerificationResult(verified=False, record=None, reason="no_provenance")

    # Recompute hashes from provided inputs
    template_path = Path(template_path)
    expected_template_hash = _hash_bytes(template_path.read_bytes())
    expected_data_hash = _hash_bytes(_canonical_json(data))

    if record.template_hash != expected_template_hash:
        return VerificationResult(verified=False, record=record, reason="template_mismatch")

    if record.data_hash != expected_data_hash:
        return VerificationResult(verified=False, record=record, reason="data_mismatch")

    # Verify the proof itself (tamper detection)
    expected_proof = _compute_proof(
        record.engine_version,
        record.template_hash,
        record.data_hash,
        record.timestamp,
    )
    if record.proof != expected_proof:
        return VerificationResult(verified=False, record=record, reason="proof_mismatch")

    return VerificationResult(verified=True, record=record, reason="match")
